[package]
name = "rust_chapter_01"
version = "0.1.0"
edition = "2021"
authors = ["Leonardo Tosetto", "<leoanrdo.a.tosetto@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
